spring.application.name=treinamento

# Configuração Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/api-docs

# ============================================
# Configuração AWS S3
# ============================================
# As credenciais AWS são obtidas automaticamente da IAM Role
# associada à EC2 via Instance Metadata Service.

# Bucket real por trás do Access Point
aws.s3.bucket-name=bucket-aws-class-4-760402326165-sa-east-1-an

# Access Point ARN (recomendado para sua configuração)
aws.s3.access-point-arn=arn:aws:s3:sa-east-1:760402326165:accesspoint/s3-aws-class-4
aws.s3.access-point-name=s3-aws-class-4

aws.s3.region=sa-east-1

# Limite de tamanho de upload
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
